
// Code generated by stanc v2.26.1
#include <stan/model/model_header.hpp>
namespace sparse_gp_model_model_namespace {


inline void validate_positive_index(const char* var_name, const char* expr,
                                    int val) {
  if (val < 1) {
    std::stringstream msg;
    msg << "Found dimension size less than one in simplex declaration"
        << "; variable=" << var_name << "; dimension size expression=" << expr
        << "; expression value=" << val;
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}

inline void validate_unit_vector_index(const char* var_name, const char* expr,
                                       int val) {
  if (val <= 1) {
    std::stringstream msg;
    if (val == 1) {
      msg << "Found dimension size one in unit vector declaration."
          << " One-dimensional unit vector is discrete"
          << " but the target distribution must be continuous."
          << " variable=" << var_name << "; dimension size expression=" << expr;
    } else {
      msg << "Found dimension size less than one in unit vector declaration"
          << "; variable=" << var_name << "; dimension size expression=" << expr
          << "; expression value=" << val;
    }
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}


using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using std::pow;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::model_base_crtp;
using stan::model::rvalue;
using stan::model::cons_list;
using stan::model::index_uni;
using stan::model::index_max;
using stan::model::index_min;
using stan::model::index_min_max;
using stan::model::index_multi;
using stan::model::index_omni;
using stan::model::nil_index_list;
using namespace stan::math;
using stan::math::pow; 

stan::math::profile_map profiles__;
static int current_statement__= 0;
static const std::vector<string> locations_array__ = {" (found before start of program)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 28, column 2 to column 30)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 29, column 2 to column 27)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 30, column 2 to column 16)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 31, column 2 to column 33)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 36, column 9 to column 10)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 36, column 2 to column 16)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 37, column 9 to column 12)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 37, column 2 to column 19)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 38, column 9 to column 12)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 38, column 2 to column 19)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 39, column 9 to column 10)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 39, column 2 to column 15)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 40, column 9 to column 10)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 40, column 2 to column 22)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 41, column 9 to column 12)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 41, column 2 to column 22)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 42, column 9 to column 10)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 42, column 12 to column 13)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 42, column 2 to column 17)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 43, column 9 to column 10)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 43, column 12 to column 13)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 43, column 2 to column 17)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 44, column 9 to column 10)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 44, column 2 to column 14)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 45, column 9 to column 10)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 45, column 12 to column 13)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 45, column 2 to column 20)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 46, column 9 to column 10)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 46, column 2 to column 15)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 47, column 9 to column 10)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 47, column 2 to column 22)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 48, column 9 to column 10)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 48, column 12 to column 13)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 48, column 2 to column 17)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 49, column 9 to column 10)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 49, column 2 to column 14)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 51, column 9 to column 10)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 51, column 12 to column 13)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 51, column 2 to column 24)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 52, column 9 to column 10)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 52, column 12 to column 13)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 52, column 2 to column 27)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 54, column 16 to column 17)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 54, column 2 to column 19)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 56, column 2 to column 29)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 58, column 2 to column 31)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 59, column 2 to column 28)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 60, column 2 to column 21)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 61, column 2 to column 21)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 64, column 2 to column 10)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 65, column 2 to column 9)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 74, column 2 to column 20)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 75, column 2 to column 23)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 77, column 2 to column 92)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 78, column 2 to column 28)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 80, column 2 to column 20)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 81, column 2 to column 21)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 83, column 2 to column 86)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 84, column 2 to column 36)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 85, column 2 to column 41)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 87, column 2 to column 26)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 89, column 2 to column 23)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 90, column 2 to column 22)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 91, column 2 to column 22)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 92, column 2 to column 24)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 93, column 2 to column 37)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 8, column 2 to column 17)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 9, column 2 to column 19)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 10, column 27 to column 28)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 10, column 2 to column 32)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 11, column 9 to column 10)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 11, column 2 to column 14)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 12, column 26 to column 29)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 12, column 2 to column 31)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 13, column 14 to column 17)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 13, column 2 to column 19)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 14, column 14 to column 17)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 14, column 2 to column 19)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 15, column 2 to column 13)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 16, column 2 to column 11)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 17, column 2 to column 14)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 18, column 2 to column 8)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 19, column 2 to column 38)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 22, column 9 to column 10)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 22, column 12 to column 13)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 22, column 2 to column 27)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 23, column 2 to column 51)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 24, column 15 to column 16)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 24, column 2 to column 18)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 25, column 2 to column 27)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 30, column 9 to column 10)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 31, column 27 to column 28)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 3, column 4 to column 25)",
                                                      " (in '/Users/aureliennioche/Documents/PythonProjects/CogModelDiscrepancy/sparse_gp_model.stan', line 2, column 37 to line 4, column 3)"};


template <typename T0__, typename T1__>
Eigen::Matrix<stan::promote_args_t<stan::value_type_t<T0__>,
T1__>, -1, 1>
u_pow(const T0__& x_arg__, const T1__& theta, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<stan::value_type_t<T0__>,
          T1__>;
  const auto& x = to_ref(x_arg__);
  const static bool propto__ = true;
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  (void) DUMMY_VAR__;  // suppress unused var warning
  
  try {
    current_statement__ = 93;
    return pow(x, theta);
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
  }
  
}

struct u_pow_functor__ {
template <typename T0__, typename T1__>
Eigen::Matrix<stan::promote_args_t<stan::value_type_t<T0__>,
T1__>, -1, 1>
operator()(const T0__& x, const T1__& theta, std::ostream* pstream__)  const 
{
return u_pow(x, theta, pstream__);
}
};

class sparse_gp_model_model final : public model_base_crtp<sparse_gp_model_model> {

 private:
  int N;
  int N_y;
  Eigen::Matrix<double, -1, 1> p;
  Eigen::Matrix<double, -1, 1> X;
  std::vector<int> y;
  std::vector<int> belong0;
  std::vector<int> belong1;
  double theta;
  double tau;
  double jitter;
  int M;
  int u_model_index;
  Eigen::Matrix<double, -1, -1> diag_jitter;
  std::vector<double> X_array;
 
 public:
  ~sparse_gp_model_model() { }
  
  inline std::string model_name() const final { return "sparse_gp_model_model"; }

  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.26.1", "stancflags = "};
  }
  
  
  sparse_gp_model_model(stan::io::var_context& context__,
                        unsigned int random_seed__ = 0,
                        std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    using local_scalar_t__ = double ;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static const char* function__ = "sparse_gp_model_model_namespace::sparse_gp_model_model";
    (void) function__;  // suppress unused var warning
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      current_statement__ = 67;
      context__.validate_dims("data initialization","N","int",
          context__.to_vec());
      N = std::numeric_limits<int>::min();
      
      current_statement__ = 67;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 67;
      current_statement__ = 67;
      check_greater_or_equal(function__, "N", N, 0);
      current_statement__ = 68;
      context__.validate_dims("data initialization","N_y","int",
          context__.to_vec());
      N_y = std::numeric_limits<int>::min();
      
      current_statement__ = 68;
      N_y = context__.vals_i("N_y")[(1 - 1)];
      current_statement__ = 68;
      current_statement__ = 68;
      check_greater_or_equal(function__, "N_y", N_y, 0);
      current_statement__ = 69;
      validate_non_negative_index("p", "N", N);
      current_statement__ = 70;
      context__.validate_dims("data initialization","p","double",
          context__.to_vec(N));
      p = Eigen::Matrix<double, -1, 1>(N);
      stan::math::fill(p, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> p_flat__;
        current_statement__ = 70;
        assign(p_flat__, nil_index_list(), context__.vals_r("p"),
          "assigning variable p_flat__");
        current_statement__ = 70;
        pos__ = 1;
        current_statement__ = 70;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 70;
          assign(p, cons_list(index_uni(sym1__), nil_index_list()),
            p_flat__[(pos__ - 1)], "assigning variable p");
          current_statement__ = 70;
          pos__ = (pos__ + 1);}
      }
      current_statement__ = 70;
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        current_statement__ = 70;
        current_statement__ = 70;
        check_greater_or_equal(function__, "p[sym1__]", p[(sym1__ - 1)], 0);}
      current_statement__ = 70;
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        current_statement__ = 70;
        current_statement__ = 70;
        check_less_or_equal(function__, "p[sym1__]", p[(sym1__ - 1)], 1);}
      current_statement__ = 71;
      validate_non_negative_index("X", "N", N);
      current_statement__ = 72;
      context__.validate_dims("data initialization","X","double",
          context__.to_vec(N));
      X = Eigen::Matrix<double, -1, 1>(N);
      stan::math::fill(X, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> X_flat__;
        current_statement__ = 72;
        assign(X_flat__, nil_index_list(), context__.vals_r("X"),
          "assigning variable X_flat__");
        current_statement__ = 72;
        pos__ = 1;
        current_statement__ = 72;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 72;
          assign(X, cons_list(index_uni(sym1__), nil_index_list()),
            X_flat__[(pos__ - 1)], "assigning variable X");
          current_statement__ = 72;
          pos__ = (pos__ + 1);}
      }
      current_statement__ = 73;
      validate_non_negative_index("y", "N_y", N_y);
      current_statement__ = 74;
      context__.validate_dims("data initialization","y","int",
          context__.to_vec(N_y));
      y = std::vector<int>(N_y, std::numeric_limits<int>::min());
      
      current_statement__ = 74;
      assign(y, nil_index_list(), context__.vals_i("y"),
        "assigning variable y");
      current_statement__ = 74;
      for (int sym1__ = 1; sym1__ <= N_y; ++sym1__) {
        current_statement__ = 74;
        current_statement__ = 74;
        check_greater_or_equal(function__, "y[sym1__]", y[(sym1__ - 1)], 0);}
      current_statement__ = 74;
      for (int sym1__ = 1; sym1__ <= N_y; ++sym1__) {
        current_statement__ = 74;
        current_statement__ = 74;
        check_less_or_equal(function__, "y[sym1__]", y[(sym1__ - 1)], 1);}
      current_statement__ = 75;
      validate_non_negative_index("belong0", "N_y", N_y);
      current_statement__ = 76;
      context__.validate_dims("data initialization","belong0","int",
          context__.to_vec(N_y));
      belong0 = std::vector<int>(N_y, std::numeric_limits<int>::min());
      
      current_statement__ = 76;
      assign(belong0, nil_index_list(), context__.vals_i("belong0"),
        "assigning variable belong0");
      current_statement__ = 77;
      validate_non_negative_index("belong1", "N_y", N_y);
      current_statement__ = 78;
      context__.validate_dims("data initialization","belong1","int",
          context__.to_vec(N_y));
      belong1 = std::vector<int>(N_y, std::numeric_limits<int>::min());
      
      current_statement__ = 78;
      assign(belong1, nil_index_list(), context__.vals_i("belong1"),
        "assigning variable belong1");
      current_statement__ = 79;
      context__.validate_dims("data initialization","theta","double",
          context__.to_vec());
      theta = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 79;
      theta = context__.vals_r("theta")[(1 - 1)];
      current_statement__ = 80;
      context__.validate_dims("data initialization","tau","double",
          context__.to_vec());
      tau = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 80;
      tau = context__.vals_r("tau")[(1 - 1)];
      current_statement__ = 81;
      context__.validate_dims("data initialization","jitter","double",
          context__.to_vec());
      jitter = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 81;
      jitter = context__.vals_r("jitter")[(1 - 1)];
      current_statement__ = 82;
      context__.validate_dims("data initialization","M","int",
          context__.to_vec());
      M = std::numeric_limits<int>::min();
      
      current_statement__ = 82;
      M = context__.vals_i("M")[(1 - 1)];
      current_statement__ = 83;
      context__.validate_dims("data initialization","u_model_index","int",
          context__.to_vec());
      u_model_index = std::numeric_limits<int>::min();
      
      current_statement__ = 83;
      u_model_index = context__.vals_i("u_model_index")[(1 - 1)];
      current_statement__ = 83;
      current_statement__ = 83;
      check_greater_or_equal(function__, "u_model_index", u_model_index, 0);
      current_statement__ = 83;
      current_statement__ = 83;
      check_less_or_equal(function__, "u_model_index", u_model_index, 1);
      current_statement__ = 84;
      validate_non_negative_index("diag_jitter", "M", M);
      current_statement__ = 85;
      validate_non_negative_index("diag_jitter", "M", M);
      current_statement__ = 86;
      diag_jitter = Eigen::Matrix<double, -1, -1>(M, M);
      stan::math::fill(diag_jitter, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 87;
      assign(diag_jitter, nil_index_list(),
        diag_matrix(rep_vector(jitter, M)), "assigning variable diag_jitter");
      current_statement__ = 88;
      validate_non_negative_index("X_array", "N", N);
      current_statement__ = 89;
      X_array = std::vector<double>(N, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 90;
      assign(X_array, nil_index_list(), to_array_1d(X),
        "assigning variable X_array");
      current_statement__ = 91;
      validate_non_negative_index("eta", "M", M);
      current_statement__ = 92;
      validate_non_negative_index("Xm", "M", M);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    num_params_r__ = 0U;
    
    try {
      num_params_r__ += 1;
      num_params_r__ += 1;
      num_params_r__ += M;
      num_params_r__ += M;
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI, stan::require_vector_like_t<VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR> log_prob_impl(VecR& params_r__,
                                                 VecI& params_i__,
                                                 std::ostream* pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    static const char* function__ = "sparse_gp_model_model_namespace::log_prob";
(void) function__;  // suppress unused var warning

    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning

    
    try {
      local_scalar_t__ kernel_length;
      kernel_length = DUMMY_VAR__;
      
      current_statement__ = 1;
      kernel_length = in__.scalar();
      current_statement__ = 1;
      if (jacobian__) {
        current_statement__ = 1;
        kernel_length = stan::math::lb_constrain(kernel_length, 0, lp__);
      } else {
        current_statement__ = 1;
        kernel_length = stan::math::lb_constrain(kernel_length, 0);
      }
      local_scalar_t__ kernel_var;
      kernel_var = DUMMY_VAR__;
      
      current_statement__ = 2;
      kernel_var = in__.scalar();
      current_statement__ = 2;
      if (jacobian__) {
        current_statement__ = 2;
        kernel_var = stan::math::lb_constrain(kernel_var, 0, lp__);
      } else {
        current_statement__ = 2;
        kernel_var = stan::math::lb_constrain(kernel_var, 0);
      }
      Eigen::Matrix<local_scalar_t__, -1, 1> eta;
      eta = Eigen::Matrix<local_scalar_t__, -1, 1>(M);
      stan::math::fill(eta, DUMMY_VAR__);
      
      current_statement__ = 3;
      eta = in__.vector(M);
      Eigen::Matrix<local_scalar_t__, -1, 1> Xm;
      Xm = Eigen::Matrix<local_scalar_t__, -1, 1>(M);
      stan::math::fill(Xm, DUMMY_VAR__);
      
      current_statement__ = 4;
      Xm = in__.vector(M);
      current_statement__ = 4;
      for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
        current_statement__ = 4;
        if (jacobian__) {
          current_statement__ = 4;
          assign(Xm, cons_list(index_uni(sym1__), nil_index_list()),
            stan::math::lub_constrain(Xm[(sym1__ - 1)], 0, 1, lp__),
            "assigning variable Xm");
        } else {
          current_statement__ = 4;
          assign(Xm, cons_list(index_uni(sym1__), nil_index_list()),
            stan::math::lub_constrain(Xm[(sym1__ - 1)], 0, 1),
            "assigning variable Xm");
        }}
      {
        current_statement__ = 5;
        validate_non_negative_index("seu", "N", N);
        Eigen::Matrix<local_scalar_t__, -1, 1> seu;
        seu = Eigen::Matrix<local_scalar_t__, -1, 1>(N);
        stan::math::fill(seu, DUMMY_VAR__);
        
        current_statement__ = 7;
        validate_non_negative_index("seu0", "N_y", N_y);
        Eigen::Matrix<local_scalar_t__, -1, 1> seu0;
        seu0 = Eigen::Matrix<local_scalar_t__, -1, 1>(N_y);
        stan::math::fill(seu0, DUMMY_VAR__);
        
        current_statement__ = 9;
        validate_non_negative_index("seu1", "N_y", N_y);
        Eigen::Matrix<local_scalar_t__, -1, 1> seu1;
        seu1 = Eigen::Matrix<local_scalar_t__, -1, 1>(N_y);
        stan::math::fill(seu1, DUMMY_VAR__);
        
        current_statement__ = 11;
        validate_non_negative_index("Mp", "N", N);
        Eigen::Matrix<local_scalar_t__, -1, 1> Mp;
        Mp = Eigen::Matrix<local_scalar_t__, -1, 1>(N);
        stan::math::fill(Mp, DUMMY_VAR__);
        
        current_statement__ = 13;
        validate_non_negative_index("f_predict", "N", N);
        Eigen::Matrix<local_scalar_t__, -1, 1> f_predict;
        f_predict = Eigen::Matrix<local_scalar_t__, -1, 1>(N);
        stan::math::fill(f_predict, DUMMY_VAR__);
        
        current_statement__ = 15;
        validate_non_negative_index("diff_eu", "N_y", N_y);
        Eigen::Matrix<local_scalar_t__, -1, 1> diff_eu;
        diff_eu = Eigen::Matrix<local_scalar_t__, -1, 1>(N_y);
        stan::math::fill(diff_eu, DUMMY_VAR__);
        
        current_statement__ = 17;
        validate_non_negative_index("L", "M", M);
        current_statement__ = 18;
        validate_non_negative_index("L", "M", M);
        Eigen::Matrix<local_scalar_t__, -1, -1> L;
        L = Eigen::Matrix<local_scalar_t__, -1, -1>(M, M);
        stan::math::fill(L, DUMMY_VAR__);
        
        current_statement__ = 20;
        validate_non_negative_index("K", "M", M);
        current_statement__ = 21;
        validate_non_negative_index("K", "M", M);
        Eigen::Matrix<local_scalar_t__, -1, -1> K;
        K = Eigen::Matrix<local_scalar_t__, -1, -1>(M, M);
        stan::math::fill(K, DUMMY_VAR__);
        
        current_statement__ = 23;
        validate_non_negative_index("f", "M", M);
        Eigen::Matrix<local_scalar_t__, -1, 1> f;
        f = Eigen::Matrix<local_scalar_t__, -1, 1>(M);
        stan::math::fill(f, DUMMY_VAR__);
        
        current_statement__ = 25;
        validate_non_negative_index("K_mp", "M", M);
        current_statement__ = 26;
        validate_non_negative_index("K_mp", "N", N);
        Eigen::Matrix<local_scalar_t__, -1, -1> K_mp;
        K_mp = Eigen::Matrix<local_scalar_t__, -1, -1>(M, N);
        stan::math::fill(K_mp, DUMMY_VAR__);
        
        current_statement__ = 28;
        validate_non_negative_index("Mm", "M", M);
        Eigen::Matrix<local_scalar_t__, -1, 1> Mm;
        Mm = Eigen::Matrix<local_scalar_t__, -1, 1>(M);
        stan::math::fill(Mm, DUMMY_VAR__);
        
        current_statement__ = 30;
        validate_non_negative_index("L_dot_eta", "M", M);
        Eigen::Matrix<local_scalar_t__, -1, 1> L_dot_eta;
        L_dot_eta = Eigen::Matrix<local_scalar_t__, -1, 1>(M);
        stan::math::fill(L_dot_eta, DUMMY_VAR__);
        
        current_statement__ = 32;
        validate_non_negative_index("A", "M", M);
        current_statement__ = 33;
        validate_non_negative_index("A", "N", N);
        Eigen::Matrix<local_scalar_t__, -1, -1> A;
        A = Eigen::Matrix<local_scalar_t__, -1, -1>(M, N);
        stan::math::fill(A, DUMMY_VAR__);
        
        current_statement__ = 35;
        validate_non_negative_index("v", "M", M);
        Eigen::Matrix<local_scalar_t__, -1, 1> v;
        v = Eigen::Matrix<local_scalar_t__, -1, 1>(M);
        stan::math::fill(v, DUMMY_VAR__);
        
        current_statement__ = 37;
        validate_non_negative_index("K_factor", "M", M);
        current_statement__ = 38;
        validate_non_negative_index("K_factor", "M", M);
        Eigen::Matrix<local_scalar_t__, -1, -1> K_factor;
        K_factor = Eigen::Matrix<local_scalar_t__, -1, -1>(M, M);
        stan::math::fill(K_factor, DUMMY_VAR__);
        
        current_statement__ = 40;
        validate_non_negative_index("K_mp_factor", "M", M);
        current_statement__ = 41;
        validate_non_negative_index("K_mp_factor", "N", N);
        Eigen::Matrix<local_scalar_t__, -1, -1> K_mp_factor;
        K_mp_factor = Eigen::Matrix<local_scalar_t__, -1, -1>(M, N);
        stan::math::fill(K_mp_factor, DUMMY_VAR__);
        
        current_statement__ = 43;
        validate_non_negative_index("Xm_array", "M", M);
        std::vector<local_scalar_t__> Xm_array;
        Xm_array = std::vector<local_scalar_t__>(M, DUMMY_VAR__);
        
        current_statement__ = 45;
        assign(Xm_array, nil_index_list(), to_array_1d(Xm),
          "assigning variable Xm_array");
        current_statement__ = 46;
        lp_accum__.add(normal_lpdf<propto__>(kernel_length, 1, 1));
        current_statement__ = 47;
        lp_accum__.add(normal_lpdf<propto__>(kernel_var, 1, 1));
        current_statement__ = 48;
        lp_accum__.add(std_normal_lpdf<propto__>(eta));
        current_statement__ = 49;
        lp_accum__.add(uniform_lpdf<propto__>(Xm, 0, 1));
        current_statement__ = 50;
        assign(Mm, nil_index_list(), Xm, "assigning variable Mm");
        current_statement__ = 51;
        assign(Mp, nil_index_list(), X, "assigning variable Mp");
        current_statement__ = 52;
        assign(K_factor, nil_index_list(), multiply(Mm, transpose(Mm)),
          "assigning variable K_factor");
        current_statement__ = 53;
        assign(K_mp_factor, nil_index_list(), multiply(Mm, transpose(Mp)),
          "assigning variable K_mp_factor");
        current_statement__ = 54;
        assign(K, nil_index_list(),
          add(
            elt_multiply(K_factor,
              gp_exp_quad_cov(to_array_1d(Xm), kernel_var, kernel_length)),
            diag_jitter), "assigning variable K");
        current_statement__ = 55;
        assign(L, nil_index_list(), cholesky_decompose(K),
          "assigning variable L");
        current_statement__ = 56;
        assign(L_dot_eta, nil_index_list(), multiply(L, eta),
          "assigning variable L_dot_eta");
        current_statement__ = 57;
        assign(f, nil_index_list(), add(Mm, L_dot_eta),
          "assigning variable f");
        current_statement__ = 58;
        assign(K_mp, nil_index_list(),
          elt_multiply(K_mp_factor,
            gp_exp_quad_cov(Xm_array, X_array, kernel_var, kernel_length)),
          "assigning variable K_mp");
        current_statement__ = 59;
        assign(A, nil_index_list(), mdivide_left_tri_low(L, K_mp),
          "assigning variable A");
        current_statement__ = 60;
        assign(v, nil_index_list(), mdivide_left_tri_low(L, L_dot_eta),
          "assigning variable v");
        current_statement__ = 61;
        assign(f_predict, nil_index_list(),
          add(Mp, multiply(transpose(A), v)), "assigning variable f_predict");
        current_statement__ = 62;
        assign(seu, nil_index_list(), elt_multiply(p, f_predict),
          "assigning variable seu");
        current_statement__ = 63;
        assign(seu0, nil_index_list(),
          rvalue(seu, cons_list(index_multi(belong0), nil_index_list()),
            "seu"), "assigning variable seu0");
        current_statement__ = 64;
        assign(seu1, nil_index_list(),
          rvalue(seu, cons_list(index_multi(belong1), nil_index_list()),
            "seu"), "assigning variable seu1");
        current_statement__ = 65;
        assign(diff_eu, nil_index_list(), subtract(seu1, seu0),
          "assigning variable diff_eu");
        current_statement__ = 66;
        lp_accum__.add(
          bernoulli_logit_lpmf<propto__>(y, multiply(tau, diff_eu)));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob_impl() 
    
  template <typename RNG, typename VecR, typename VecI, typename VecVar, stan::require_vector_like_vt<std::is_floating_point, VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr, stan::require_std_vector_vt<std::is_floating_point, VecVar>* = nullptr>
  inline void write_array_impl(RNG& base_rng__, VecR& params_r__,
                               VecI& params_i__, VecVar& vars__,
                               const bool emit_transformed_parameters__ = true,
                               const bool emit_generated_quantities__ = true,
                               std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.resize(0);
    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    static const char* function__ = "sparse_gp_model_model_namespace::write_array";
(void) function__;  // suppress unused var warning

    (void) function__;  // suppress unused var warning

    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning

    
    try {
      double kernel_length;
      kernel_length = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 1;
      kernel_length = in__.scalar();
      current_statement__ = 1;
      kernel_length = stan::math::lb_constrain(kernel_length, 0);
      double kernel_var;
      kernel_var = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 2;
      kernel_var = in__.scalar();
      current_statement__ = 2;
      kernel_var = stan::math::lb_constrain(kernel_var, 0);
      Eigen::Matrix<double, -1, 1> eta;
      eta = Eigen::Matrix<double, -1, 1>(M);
      stan::math::fill(eta, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 3;
      eta = in__.vector(M);
      Eigen::Matrix<double, -1, 1> Xm;
      Xm = Eigen::Matrix<double, -1, 1>(M);
      stan::math::fill(Xm, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 4;
      Xm = in__.vector(M);
      current_statement__ = 4;
      for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
        current_statement__ = 4;
        assign(Xm, cons_list(index_uni(sym1__), nil_index_list()),
          stan::math::lub_constrain(Xm[(sym1__ - 1)], 0, 1),
          "assigning variable Xm");}
      vars__.emplace_back(kernel_length);
      vars__.emplace_back(kernel_var);
      for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
        vars__.emplace_back(eta[(sym1__ - 1)]);}
      for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
        vars__.emplace_back(Xm[(sym1__ - 1)]);}
      if (logical_negation((primitive_value(emit_transformed_parameters__) ||
            primitive_value(emit_generated_quantities__)))) {
        return ;
      } 
      if (logical_negation(emit_generated_quantities__)) {
        return ;
      } 
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // write_array_impl() 
    
  template <typename VecVar, typename VecI, stan::require_std_vector_t<VecVar>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void transform_inits_impl(const stan::io::var_context& context__,
                                   VecI& params_i__, VecVar& vars__,
                                   std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.clear();
    vars__.reserve(num_params_r__);
    
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      double kernel_length;
      kernel_length = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 1;
      kernel_length = context__.vals_r("kernel_length")[(1 - 1)];
      double kernel_length_free__;
      kernel_length_free__ = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 1;
      kernel_length_free__ = stan::math::lb_free(kernel_length, 0);
      double kernel_var;
      kernel_var = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 2;
      kernel_var = context__.vals_r("kernel_var")[(1 - 1)];
      double kernel_var_free__;
      kernel_var_free__ = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 2;
      kernel_var_free__ = stan::math::lb_free(kernel_var, 0);
      Eigen::Matrix<double, -1, 1> eta;
      eta = Eigen::Matrix<double, -1, 1>(M);
      stan::math::fill(eta, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> eta_flat__;
        current_statement__ = 3;
        assign(eta_flat__, nil_index_list(), context__.vals_r("eta"),
          "assigning variable eta_flat__");
        current_statement__ = 3;
        pos__ = 1;
        current_statement__ = 3;
        for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
          current_statement__ = 3;
          assign(eta, cons_list(index_uni(sym1__), nil_index_list()),
            eta_flat__[(pos__ - 1)], "assigning variable eta");
          current_statement__ = 3;
          pos__ = (pos__ + 1);}
      }
      Eigen::Matrix<double, -1, 1> Xm;
      Xm = Eigen::Matrix<double, -1, 1>(M);
      stan::math::fill(Xm, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> Xm_flat__;
        current_statement__ = 4;
        assign(Xm_flat__, nil_index_list(), context__.vals_r("Xm"),
          "assigning variable Xm_flat__");
        current_statement__ = 4;
        pos__ = 1;
        current_statement__ = 4;
        for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
          current_statement__ = 4;
          assign(Xm, cons_list(index_uni(sym1__), nil_index_list()),
            Xm_flat__[(pos__ - 1)], "assigning variable Xm");
          current_statement__ = 4;
          pos__ = (pos__ + 1);}
      }
      Eigen::Matrix<double, -1, 1> Xm_free__;
      Xm_free__ = Eigen::Matrix<double, -1, 1>(M);
      stan::math::fill(Xm_free__, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 4;
      for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
        current_statement__ = 4;
        assign(Xm_free__, cons_list(index_uni(sym1__), nil_index_list()),
          stan::math::lub_free(Xm[(sym1__ - 1)], 0, 1),
          "assigning variable Xm_free__");}
      vars__.emplace_back(kernel_length_free__);
      vars__.emplace_back(kernel_var_free__);
      for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
        vars__.emplace_back(eta[(sym1__ - 1)]);}
      for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
        vars__.emplace_back(Xm_free__[(sym1__ - 1)]);}
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // transform_inits_impl() 
    
  inline void get_param_names(std::vector<std::string>& names__) const {
    
    names__.clear();
    names__.emplace_back("kernel_length");
    names__.emplace_back("kernel_var");
    names__.emplace_back("eta");
    names__.emplace_back("Xm");
    } // get_param_names() 
    
  inline void get_dims(std::vector<std::vector<size_t>>& dimss__) const {
    dimss__.clear();
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(M)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(M)});
    
    } // get_dims() 
    
  inline void constrained_param_names(
                                      std::vector<std::string>& param_names__,
                                      bool emit_transformed_parameters__ = true,
                                      bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "kernel_length");
    param_names__.emplace_back(std::string() + "kernel_var");
    for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "eta" + '.' + std::to_string(sym1__));
      }}
    for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "Xm" + '.' + std::to_string(sym1__));
      }}
    if (emit_transformed_parameters__) {
      
    }
    
    if (emit_generated_quantities__) {
      
    }
    
    } // constrained_param_names() 
    
  inline void unconstrained_param_names(
                                        std::vector<std::string>& param_names__,
                                        bool emit_transformed_parameters__ = true,
                                        bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "kernel_length");
    param_names__.emplace_back(std::string() + "kernel_var");
    for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "eta" + '.' + std::to_string(sym1__));
      }}
    for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "Xm" + '.' + std::to_string(sym1__));
      }}
    if (emit_transformed_parameters__) {
      
    }
    
    if (emit_generated_quantities__) {
      
    }
    
    } // unconstrained_param_names() 
    
  inline std::string get_constrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"kernel_length\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"kernel_var\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"eta\",\"type\":{\"name\":\"vector\",\"length\":" << M << "},\"block\":\"parameters\"},{\"name\":\"Xm\",\"type\":{\"name\":\"vector\",\"length\":" << M << "},\"block\":\"parameters\"}]";
    return s__.str();
    } // get_constrained_sizedtypes() 
    
  inline std::string get_unconstrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"kernel_length\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"kernel_var\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"eta\",\"type\":{\"name\":\"vector\",\"length\":" << M << "},\"block\":\"parameters\"},{\"name\":\"Xm\",\"type\":{\"name\":\"vector\",\"length\":" << M << "},\"block\":\"parameters\"}]";
    return s__.str();
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    inline void write_array(RNG& base_rng,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                            const bool emit_transformed_parameters = true,
                            const bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      std::vector<double> vars_vec(vars.size());
      std::vector<int> params_i;
      write_array_impl(base_rng, params_r, params_i, vars_vec,
          emit_transformed_parameters, emit_generated_quantities, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i) {
        vars.coeffRef(i) = vars_vec[i];
      }
    }

    template <typename RNG>
    inline void write_array(RNG& base_rng, std::vector<double>& params_r,
                            std::vector<int>& params_i,
                            std::vector<double>& vars,
                            bool emit_transformed_parameters = true,
                            bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      write_array_impl(base_rng, params_r, params_i, vars, emit_transformed_parameters, emit_generated_quantities, pstream);
    }

    template <bool propto__, bool jacobian__, typename T_>
    inline T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
                       std::ostream* pstream = nullptr) const {
      Eigen::Matrix<int, -1, 1> params_i;
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }

    template <bool propto__, bool jacobian__, typename T__>
    inline T__ log_prob(std::vector<T__>& params_r,
                        std::vector<int>& params_i,
                        std::ostream* pstream = nullptr) const {
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }
  

    inline void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream = nullptr) const final {
      std::vector<double> params_r_vec(params_r.size());
      std::vector<int> params_i;
      transform_inits_impl(context, params_i, params_r_vec, pstream);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i) {
        params_r.coeffRef(i) = params_r_vec[i];
      }
    }
    inline void transform_inits(const stan::io::var_context& context,
                                std::vector<int>& params_i,
                                std::vector<double>& vars,
                                std::ostream* pstream = nullptr) const final {
      transform_inits_impl(context, params_i, vars, pstream);
    }        

};
}
using stan_model = sparse_gp_model_model_namespace::sparse_gp_model_model;

#ifndef USING_R

// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}

stan::math::profile_map& get_stan_profile_data() {
  return sparse_gp_model_model_namespace::profiles__;
}

#endif


